### ISSUE TITLE
US1 - Create Dog Profiles

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#1]
## Value proposition

As a user
I want to create a profile for my dog
In order to manage all important informations

## Description

<img width="386" alt="Bildschirmfoto 2023-08-12 um 14 06 20" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/c20fc413-cb4c-43e1-a13f-01f5b77fa5a4">

### on the overview page:
- [x] there is a list of all profiles
- [x] every list item has the same height
- [x] every list item shows: name, breed and age
- [x] the list can only be scrolled vertically
- [x] on top of the page there is a button to create a new profile
- [x] when clicked, a form opens

### on the form page
- [x] the form contains a headline
- [x] the form containts fields to input following informations: name, birthday, breed
- [x] the form has a button at the bottom
- [x] when clicked, the user is redirected to the overview page
- [x] the recently created profile shows up at the top of the page

## Tasks

- [x] `create a branch feat/dog-profile-form`

### for the overview page
- [x] create a dump button  component
- [x] create a component for the list
- [x] map over the array of the pets
- [x] create a component for the list item 
- [x] display the given information from a single pet in the list item

### for the form page
- [x] create a new page
- [x] create a component for the form
- [x] input and label to insert the information
- [x] use the dump component for the submit button
- [x] write the handleSubmit function
- [x] useState and uid() for pet profiles as an array with objects
{id: uid(), name: “ ”, birthday: “ “, breed: “ “}
- [x] the inserted birthday will be transformed into the age (new Date... ; calculate the age)

## Size - S
I expect to take 1 to 2 hours to complete
