### ISSUE TITLE
US8 - Form Feedback

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#12]
## Value proposition

As an user
I want to see a confirmation message after submitting the form
In order to check, if the submission was successful

## Description

<img width="373" alt="Bildschirmfoto 2023-08-21 um 08 57 48" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/6f7a19da-5bf3-4731-a1d4-1cf580bb17e1">

## Acceptance criteria

- [x] After submitting the form there is a short success message
- [x] the loading message disappears after a short time

## Tasks

- [x] `create a branch feat/form-feedback`
- [x] make the deleteModal a dumb component
- [x] track if the form added a new pet to the list
- [x] track if the form updated the pet
- [x] add a timing function to let the modal disappear after a short time

## Size - S
I expect to take up to 2 hours to complete
