### ISSUE TITLE
US7 - Input Adjustmesnts

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#13]
## Value proposition

As an user
I want to see the age of my puppy in days and don't want to be able to select the same breed twice
In order to have even better access to the given information

## Description

<img width="765" alt="Bildschirmfoto 2023-08-21 um 08 19 26" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/3c71e432-b49c-4b17-951e-9a4e57ff1fd4">

## Acceptance criteria

- [x] I can't enter a birthday before 2000
- [x] I see the age of my puppy in days, when it's younger than one month
- [x] I can't select the same breed twice

## Tasks

- [x] `create a branch feat/input-adjustments`
- [x] add a min and max value to the birthday input
- [x] add a function to track the selected breed and disable the selected. for the next breed select
- [x] adjust the age calculator to also get the days for young puppies

## Size - M
I expect to take 2 -4 hours to complete
