### ISSUE TITLE
US9 - Dog Food

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#16]
## Value proposition

As an user
I want to add the food of my dog
In order to manage the stock and price informations

## Description

<img width="384" alt="Bildschirmfoto 2023-08-21 um 11 49 03" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/66009c61-14cc-49bb-8cb9-98bea411d93a">

### On the form
- [x] there should be a section for the food
- [x] I can add the name, the type, the size, daily ration for my dog and price, I can also add the current stock

### On the details Page
- [x] I can see the food I added
- [x] I can see how much the food costs me a day
- [x] I can see the current stock and add a new bag or multiple cans

## Tasks

- [x] `create a branch feat/dog-food`
- [x] add a fieldset for the food to the form
- [x] add inputs related to the needed information (name, price, bag size, etc.)
- [x] add a function that refills the current stock based on the given bag size
- [x] when the user chose cans instead of bags there should be a number input to add X cans
- [x] add a calculate function, that calculated the price for a day with the given bag price, size and daily need
- [x] add a function that calculates the stock and handles the update stock

## Size - M
I expect to take up to 4 hours to complete

**Comment by alperkuertuel** [comment]
I like that you can estimate how much time it is going to take.  LGTM.

**Comment by FabianRuettgers** [comment]
The Feature Works and I will approve you.

Otherwise, from that, here are a few notes.
/pets/[id] Page:
- for the telephone number I can input text, you should consider only allowing numbers
- there isn't a label for the refill input, you should consider adding a label-element or an aria-label
- the semantic structure of the page's headlines is mixed up, you're using a h3 for the vet section, after that a h2 for the card section and then a h4 for the Current Stock

/pets : 
- there isn't a label for the breed selector, you should consider adding a label-element or an aria-label
