### ISSUE TITLE
US2 - Fetch Dog Data

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#2]
## Value proposition

As an user 
I want to get a list of all breeds, when creating a new profile
So that I don't have to write the breed myself.

## Description

<img width="771" alt="Bildschirmfoto 2023-08-12 um 14 31 16" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/992375e3-d0b2-4d58-8ad7-7e78cf396ee1">

### when creating a new profile
- [x] there is an input field with an arrow
- [x] when clicked, a dropdown opens with all dog breeds
- [x] I can select one
- [x] when I click on one breed, the dropdown closes and the clicked one is picked

## Tasks

- [x] `create a branch feat/dog-data-fetching`
- [x] get an auth key for the API  ` https://thedogapi.com/ `

### in _app.js
- [x] fetcher
- [x] useState
- [x] fetch function / useSWR
- [x] prop with data to <Component />

### on form page
- [x] select input
- [x] map over the data array to create an option field for each breed
- [x] add value and key for every option

## Size - S
I expect to take 1 to 2 hours to complete

**Comment by milodevhh** [comment]
Hey Nina, already wonderful, maybe you add to the dropdown a search?  Just thought ;) - it will help the user to find the breed in a shorter time, I am not that deep into the world of breeds, but there are a lot? For the section "on form page" you can describe more in detail.
