### ISSUE TITLE
US10 - Breed List and Page

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#20]
## Value proposition

As an user
I want to see a list of all existing breeds and a details page with informations about the breed
In order to inform myself

## Description

<img width="500" alt="Bildschirmfoto 2023-08-23 um 16 28 54" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/ec097986-b5be-427b-a45b-b4421e6b45bb">

## Acceptance criteria

- [x] there is a navigation bar on the bottom
- [x] there is a header with a logo
- [x] there are two links (pet list / breed list)
- [x] when clicking on the breed list I can see a list of all existing breeds in alphabetical order
- [x] when clicking on one breed I can see a details page with informations about the breed

## Tasks

- [x] `create a branch feat/breed-info-page`
- [x] create a new page for the breed list
- [x] map over the breeds from the current API
- [x] if api not available handle error state / loading state
- [x] li has breed name and an image
- [x] li is a link
- [x] dynamic route to the breed details page
- [x] image and more information of the breed from a second api
- [x] secure api key and handle error and loading state
- [x] create a layout component for the navigation
- [x] add a logo to the top

## Size - M
I expect to take 4 - 8 hours to complete

**Comment by FabianRuettgers** [comment]
- If the API requires an API key, make sure to handle its integration and management securely.
- Consider scenarios where the API might fail to load, or the data might not be available. Plan for appropriate error handling in such cases.

**Comment by ninaassmann** [comment]
thanks I updated that
