### ISSUE TITLE
US11 - Filter Breed Info List

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#22]
## Value proposition

As an user
I want to be able to filter the breed list on the info page
So that I can see only the breeds I am looking for

## Description

<img width="300" alt="Bildschirmfoto 2023-08-24 um 15 18 55" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/110c3477-e342-4658-8170-4ded74c52be0">

## Acceptance criteria

- [x] On the breeds page there are filter buttons on the top
- [x] when a filter is clicked, a dropdown opens with the possible filter settings
- [x] possible filter:
(breed group, origin, height (small, medium, large _not sure how to get this now, cause the height ist like height: "53 - 60"_ )
- [x] when I filter I only what to see the matching breeds
- [x] I can use more than one filter at a time

## Tasks

- [x] `create a branch feat/breed-filter`
- [x] create buttons (dropdown) for the filter
- [x] create function to create a filtered array
- [x] create a function to combine two filter
- [x] find a solution for the height filter

## Size - M
I expect to take up to 6 hours to complete

**Comment by F-Kirchhoff** [comment]
Hey Nina,
for now its not quite clear how the user should enter a specific origin/height/or breed. Is it via a dropdown menu / text input etc? Please update your user story in that regard.
And you have a typo in your value proposition: `So that I can only "see" ...`
