### ISSUE TITLE
US13 - Form improvement

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#23]
## Value proposition

As an user
I want to have an easier form
So that I don't get overwhelmed

## Description

<img width="756" alt="Bildschirmfoto 2023-08-24 um 15 54 26" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/f1ab1c2c-a9d0-4fe0-8d51-c37d7ee48440">

## Acceptance criteria

- [ ] when I click on create new dog I get on an interview-like form
- [ ] every page is just one question (input) except for the vet and food info
- [ ] I can go back to the prev question
- [ ] I can cancel and go back to the overview
- [ ] on top I can see a progress bar (didn't do that, maybe in a later US)
- [ ] hide the food and vet section, when the user don't want to input them

## Tasks

- [ ] `create a branch feat/form-improvement`
- [ ] state for the steps (
- [ ] state for the newPet to track the input changes
- [ ] prev and next buttons
- [ ] function to show/hide the food and vet section

## Size - M
I expect to take up to 8 hours to complete
