### ISSUE TITLE
US14 - Profile Image

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#24]
## Value proposition

As an user
I want to select a profile image for my pet

## Description

<img width="1112" alt="Bildschirmfoto 2023-08-24 um 16 29 07" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/bc747883-c811-4ea5-bf91-7c9a544a01ac">

## Acceptance criteria

- [ ] on the form page after the name input there is a image selection with predefined dog illustrations
- [ ] I can choose one of them as a profile image for the dog
- [ ] both the pet list and pet details page showing the selected image
- [ ] when there is none selected, a default image is shown

## Tasks

- [ ] `create a branch feat/profile-image`
- [ ] create a new step for the form
- [ ] add an array of dog illustrations
- [ ] there is a grid for the dog images, they are clickable, only one can be selected
- [ ] it's not required
- [ ] add a default images for all dogs
- [ ] when selected, the reference id is added to the pet object

## Size - S
I expect to take up to 2 hours to complete
