### ISSUE TITLE
US12 - Image Loading Improvement

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#26]
## Value proposition

As an user
I want to see multiple pages in the breed list
In order to have a better performance of the app

## Description

<img width="304" alt="Bildschirmfoto 2023-08-29 um 10 51 47" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/716ab10a-3088-48f8-8426-5face29765fd">

## Acceptance criteria

- [x] On the breed list page I can only see twenty entries at a time
- [x] On the bottom there are two buttons to swap pages and show the next / prev entries
- [x] ALTERNATIV - there is a load more button, that loads the next 20 on the bottom of the current list
- [x] when new Entries are loading I can see a loading state

## Tasks

- [x] `create a branch feat/image-loading-improvement`
- [x] split the given breeds data array in smaller ones via slice
- [x] adjust the start / end index when clicking on the buttons next / prev
- [x] add a loading state for the entries

**Comment by mariusgolabski** [comment]
LGTM :thumbsup:
