### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#29]
## Value proposition

As an user
I want to see a beautiful UI
In order to have a better access and user experience

## Description

<img width="1192" alt="Bildschirmfoto 2023-09-04 um 10 09 44" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/ed13e020-4cf8-43bd-b7d0-45add389d376">

## Acceptance criteria

- [ ] there is a consistent styling
- [ ] there is enough padding around the objects
- [ ] the buttons are significant

## Tasks

- [ ] `create a branch styling`
- [ ] create variables for colors, fonts and spacing
- [ ] clean up the styled components
