### ISSUE TITLE
US3 - Dog Profile Page

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#3]
## Value proposition

As an user
I want to see a new page, when I click on one of the list items
In order to see more informations suitable for the breed

## Description

<img width="366" alt="Bildschirmfoto 2023-08-14 um 08 59 37" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/547203ff-c755-4269-ba83-147e2c882c35">

### On the Overview Page
- [x] the list items are clickable
- [x] when clicked, a new page open

### On the Profile Page
- [x] at the top of the page there is a button to get back to the overview
- [x] I can see the informations I inserted for this profile (name, age and breed)
- [x] I can see information that fits the breed

## Tasks

- [x] `create a branch feat/profile-page`

### For the Overview Page
- [x] the list items are clickable
- [x] add a hover state

### For the Profile Page
- [x] create a dynamic route for the dog profiles
useRouter()
- [x] display a button at the top "back to Overview"
- [x] display information from the state
- [x] display information from the API depending on the inserted breed

## Size - S to M
I expect to take 2 to 4 hours to complete

**Comment by jonas8900** [comment]
LGTM !
