### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#30]
## Value proposition

As an user
I want to have the option to change to the dark mode and back
In order to see the web app in my preferred theme

## Description

<img width="864" alt="Bildschirmfoto 2023-09-04 um 10 16 55" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/eedd285f-29f2-41b0-8198-c6a35ab0cbe7">

## Acceptance criteria

- [ ] in the top right corner there is a button to switch the theme
- [ ] when clicked, the theme switched

## Tasks

- [ ] `create a branch feat/theme`
- [ ] add dark mode stylings
- [ ] add button to the header
- [ ] add function to switch the theme
