### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#31]
## Value proposition

As an user
I want to have a good access, even if I'm disabled in any kind of way

## Description

- no changes to the UI, just when read out loud

## Acceptance criteria

- [x] I get information about the things on the web app, when it's read out loud

## Tasks

- [x] `create a branch feat/accessibilityt`
- [x] add aria-label and aria-labelledby when needed
