### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#35]
## Value proposition

As an developer
I want to connect my app with mongoDB
In order to not only have access via the local Storage and be able to use a login in the future

## Description

no UI changes here

## Acceptance criteria

- [ ] I can add a pet on one device and see it on another // no more localStorage

## Tasks

- [ ] `create a branch feat/mongodb`
- [ ] connect my app with mongodb atlas
- [ ] change from localStorage to mongoDB
- [ ] adjust the vercel settings
- [ ] create the backend
- [ ] dive deep into the handouts, cause I'm not sure how exactly to do that^^

**Comment by milodevhh** [comment]
As a developer, I would say, have fun with this task!
