### ISSUE TITLE
Login Page and NextAuth

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#37]
## Value proposition

As an user
I want to login to my personal account
In order to just see my own pets

## Description

- the first page to show is the login page with e.g. google or github login
- there is a logout button in the header

## Acceptance criteria

- [ ] When I open the app, I first see a login page
- [ ] I can Login via Provider (e.g. Google, GitHub)
- [ ] when logged In, I only see my own pets
- [ ] I can log out

## Tasks

- [ ] `create a branch feat/login`
- [ ] implement nextAuth
- [ ] create a login page
- [ ] add userId to the pets
- [ ] only show pets, that match the user
- [ ] logout button
