### ISSUE TITLE
US 4 - Mixed Breed Select

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#4]
## Value proposition

As an user
I want to be able to add more than one breed
In order to create a profile for a mixed breed

## Description

<img width="1125" alt="Bildschirmfoto 2023-08-14 um 09 05 58" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/3dd76375-a475-4cf2-b67d-31b1aa45d7c3">
<img width="735" alt="Bildschirmfoto 2023-08-14 um 09 14 34" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/5e8d8538-18c1-4a11-b4af-5d0a60e0d2df">

### On the form
- [x] the is a button for "mixed breed"
- [x] when clicked there will be a button under the breed select with a plus
- [x] when clicked, there is another breed select, so that I can add more than one breed
- [x] there is no need to add another breed - it can be one breed and mixed

### On the overview / profile page
- [x] I can see the multiple breed seperated with a comma
- [x] there is also a label with "mixed"

## Tasks

- [x] `create a branch feat/mixed-breed`

### For the Form Page
- [x] use dump button component for the mixed breed (maybe a checkbox input)
- [x] add a plus button under the breed select
- [x] create a function to add the plus button
- [x] display another breed select when clicked
- [x] create a function to add another breed select input
- [x] update the handleSubmit

### For the Overview / Profile Page
- [x] add the multiple breeds to the information area

## Size - M
I expect to take 4 to 8 hours to complete
(could be an issue with the multiple select inputs)

**Comment by milodevhh** [comment]
Hey Nina, sounds good to me! Have fun with that!

**Comment by FabianRuettgers** [comment]
### Issue with Feedback on Form Submission: 
- The form doesn't provide any feedback upon submission. It would be helpful to have a confirmation message or notification indicating that the submission was successful.


### Future Birthdays Allowed: 
- The form allows users to enter a birthday that's set in the future. It might be a good idea to validate and restrict the entry of future dates.


### Unknown Dog Breed Option: 
- It would be clever to include an "Unknown Breed" option in the breed selection, as some users might not be aware of their dog's breed.


### Duplicate Dog Breed Addition: 
- The form allows the same dog breed to be added repeatedly. Consider limiting duplicate entries to maintain data accuracy.


### Age Display for Young Pets: 
- When I create a pet with today's birthday, the list view displays the age as 11 months, while the details page shows the age as 0 months.


- When a pet's age is under 1 month, it would make more sense to display the age in days rather than months. This would provide more accurate information to users.
