### ISSUE TITLE
US5 - Vet Information

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#5]
## Value proposition

As an user
I want to add the contact information about my vet
In order to get a fast access to the vet in case of an emergency

## Description

<img width="748" alt="Bildschirmfoto 2023-08-14 um 09 33 50" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/473236ab-b183-4c93-a4c5-44c47e5d1263">

### On the Form
- [x] in the form there are some new input fields at the bottom
- [x] I can add the name of the vet, the address and the phone number
- [x] the vet input area stands out visually

### On the Profile Page
- [x] at the bottom of the page, I can find an area with the vet information
- [x] I can click on that
- [x] when I am using my phone to open this app, when clicked, I automatically am calling my vet

## Tasks

- [x] `create a branch feat/vet-information`

### For the Form Page
- [x] add a fieldset for the vet information
- [x] add three inputs (name, address, phone)
- [x] update the handleSubmit function

### For the Profile Page
- [x] add the vet informations at the bottom
- [x] add a Link Component
- [x] the section should be clickable with the vet phone number as href tel:123456789

## Size - S
I expect to take 1 to 2 hours to complete
