### ISSUE TITLE
US6 - Update & Delete

### ISSUE THREAD

**Issue by ninaassmann** [ninaassmann/nf-capstone-project#9]
## Value proposition

As an user
I want to update and delete my pets
In order to change Information or delete them.

## Description

<img width="1136" alt="Bildschirmfoto 2023-08-17 um 11 59 34" src="https://github.com/ninaassmann/nf-capstone-project/assets/97239098/a51d5755-16fc-41ff-a17a-c704693c8244">

### On the Profile Page
- [ ] there is an edit button on the top right
- [ ] there is an delete button on the bottom
- [ ] when clicked edit I get to the form page, prefilled with the current Informations (the button on the bottom is "Update Pet")
- [ ] when clicked delete, there is a popup to confirm
- [ ] when confirmed, I get back to the overview

## Tasks

- [ ] `create a branch feat/update-delete`
- [ ] add two buttons (delete, edit) to the [slug].js
- [ ] add handleUpdate and handleDelete functions
- [ ] the update form should be prefilled
- [ ] there should be a popup for the delete function (accept delete / cancel delete)

## Size - S to M
I expect to take 2 - 4 hours to complete.

**Comment by milodevhh** [comment]
Looks good! Have fun with it... You can also call a popup as a modal ;)
